export const images =
  [{
    original: '/images/2023-06-0611.34.12.jpg',
    thumbnail: '/images/2023-06-0611.34.12.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img031.jpg',
    thumbnail: '/images/img031.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img151.jpg',
    thumbnail: '/images/img151.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img161.jpg',
    thumbnail: '/images/img161.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img071.jpg',
    thumbnail: '/images/img071.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img141.jpg',
    thumbnail: '/images/img141.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img081.jpg',
    thumbnail: '/images/img081.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img121.jpg',
    thumbnail: '/images/img121.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img131.jpg',
    thumbnail: '/images/img131.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img021.jpg',
    thumbnail: '/images/img021.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img041.jpg',
    thumbnail: '/images/img041.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img051.jpg',
    thumbnail: '/images/img051.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img111.jpg',
    thumbnail: '/images/img111.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img001.jpg',
    thumbnail: '/images/img001.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img011.jpg',
    thumbnail: '/images/img011.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img06.jpg',
    thumbnail: '/images/img06.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img10.jpg',
    thumbnail: '/images/img10.jpg',
    thumbnailHeight: 70
  }, {
    original: '/images/img091.jpg',
    thumbnail: '/images/img091.jpg',
    thumbnailHeight: 70
  }]